// File generated by FlutterFire CLI — replace with your project config:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for PhysiqueLab.
/// Run `flutterfire configure` to overwrite with your Firebase project keys.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Placeholder values — replace via `flutterfire configure` before release.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE-OQiFhCYo2gWcssLC4NdLF9Wu32E2kU',
    appId: '1:251351432431:web:e2e7a483ad59de47c66f1a',
    messagingSenderId: '251351432431',
    projectId: 'physiquelab-f4daf',
    authDomain: 'physiquelab-f4daf.firebaseapp.com',
    storageBucket: 'physiquelab-f4daf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'physiquelab',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'physiquelab',
    iosBundleId: 'com.physiquelab.physiqueLab',
  );

  static const FirebaseOptions macos = ios;
}
